# syntax=docker/dockerfile:1
FROM golang:1.16 as builder
WORKDIR /go/src/github.com/alexellis/href-counter/
RUN go get -d -v golang.org/x/net/html
COPY main.go ./
COPY go.mod ./
COPY go.sum ./
RUN go mod download &&   CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o main .

FROM ubuntu:latest as post-runner
WORKDIR /root/
COPY --from=builder /go/src/github.com/alexellis/href-counter/main ./
COPY entrypoint.sh ./

FROM ubuntu:latest as runner
WORKDIR /root/
COPY --from=post-runner /root/main ./
COPY --from=post-runner /root/entrypoint.sh ./
RUN apt-get update && \
  apt-get install -y htop && \
  apt-get clean
EXPOSE 8080
ENTRYPOINT ["./entrypoint.sh"]
